<?php 
    include('../config/constants.php'); 

    if(!isset($_SESSION['user_role']) || $_SESSION['user_role'] !== 'staff') { exit; }

    $type = $_GET['type'] ?? 'weekly';
    $title = "Sales Report";
    $query_filter = "";

    // Set logic based on report type
    if($type == 'weekly') {
        $title = "Weekly Sales Summary (" . date('W') . ")";
        $query_filter = "WHERE YEARWEEK(order_date, 1) = YEARWEEK(CURDATE(), 1)";
    } elseif($type == 'monthly') {
        $title = "Monthly Revenue Audit (" . date('F Y') . ")";
        $query_filter = "WHERE MONTH(order_date) = MONTH(CURRENT_DATE()) AND YEAR(order_date) = YEAR(CURRENT_DATE())";
    } elseif($type == 'products') {
        $title = "Best Selling Products Analytics";
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title><?php echo $title; ?></title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; color: #2f3542; }
        .report-header { border-bottom: 2px solid #ff4757; padding-bottom: 20px; margin-bottom: 30px; display: flex; justify-content: space-between; align-items: center; }
        .report-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .report-table th { background: #f1f2f6; padding: 12px; text-align: left; border: 1px solid #ddd; }
        .report-table td { padding: 12px; border: 1px solid #ddd; }
        .summary-box { background: #2f3542; color: white; padding: 20px; border-radius: 8px; text-align: right; }
        @media print { .print-btn { display: none; } }
    </style>
</head>
<body onload="window.print()">
    <div class="report-header">
        <div>
            <h1 style="margin: 0;"><?php echo $title; ?></h1>
            <p style="color: #747d8c; margin: 5px 0;">Generated by: <?php echo $_SESSION['staff_username'] ?? 'System Admin'; ?> | Date: <?php echo date('d M Y, H:i'); ?></p>
        </div>
        <button class="print-btn" onclick="window.print()" style="padding: 10px 20px; background: #ff4757; color: white; border: none; border-radius: 5px; cursor: pointer;">Print Report</button>
    </div>

    <table class="report-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Order Date</th>
                <th>Grand Total</th>
                <th>Delivery Fee</th>
                <th>Revenue</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                $sql = "SELECT * FROM `ORDER` $query_filter ORDER BY order_date DESC";
                $res = mysqli_query($conn, $sql);
                $total_rev = 0;

                while($row = mysqli_fetch_assoc($res)) {
                    $order_rev = $row['grand_total'] - $row['delivery_charge'];
                    $total_rev += $order_rev;
            ?>
                <tr>
                    <td>#<?php echo $row['order_ID']; ?></td>
                    <td><?php echo date('d M Y, H:i', strtotime($row['order_date'])); ?></td>
                    <td>RM <?php echo number_format($row['grand_total'], 2); ?></td>
                    <td>RM <?php echo number_format($row['delivery_charge'], 2); ?></td>
                    <td style="font-weight: bold;">RM <?php echo number_format($order_rev, 2); ?></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>

    <div class="summary-box">
        <h3 style="margin: 0;">Net Sales Revenue: <span style="color: #2ecc71; margin-left: 15px;">RM <?php echo number_format($total_rev, 2); ?></span></h3>
    </div>

    <p style="text-align: center; margin-top: 50px; font-size: 0.8rem; color: #a4b0be;">MCOS Management System - Confidential Internal Report</p>
</body>
</html>